### ISSUE TITLE
VnV Review #1 - Missing references

### ISSUE THREAD

**Issue by adrian-soch** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#12]
In:
https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/blob/b8c5c7c4de572ebb165e46d429c47cdf18bc7b61/docs/VnVPlan/VnVPlan.tex#L49
You mention the SRS, but there is no reference or link to that document. I recommend adding a references/bibliography section. Other documents mentioned in Section 2.3 also require references.

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `56932c7`

**Date Resolved:** `04/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/56932c79f8bf82cd6661a36e9018ec762a10a474)

**Related Issue:** #9 

### Summary of Changes
Added Hyperlinks for relevant sections. Included missing text.
