### ISSUE TITLE
VnV Review #2 - SRS Verification Plan

### ISSUE THREAD

**Issue by adrian-soch** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#13]
Section 3.2 does not provide the actual checklist for reviewers.

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `416ba93`

**Date Resolved:** `05/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/416ba93a360140ae240ba98fd1be1d662c199cfa)

### Summary of Changes
A checklist section was added.
