### ISSUE TITLE
VnV Review #3 - Design Verification Plan

### ISSUE THREAD

**Issue by adrian-soch** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#14]
In: https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/blob/b8c5c7c4de572ebb165e46d429c47cdf18bc7b61/docs/VnVPlan/VnVPlan.tex#L133
you do not provide a reference to the 'best practices', this section is a little vague in describing how a reviewer can actually verify your design.

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `0ef95f2`

**Date Resolved:** `17/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/0ef95f297b031d89847dce2f3b448fa691233af0)

**Related Issue:** #9 

### Summary of Changes
The design Verification plan is updated with more detail and best practices has also been mentioned.
