### ISSUE TITLE
VnV Review #4 - Verification and Validation Plan Verification Plan

### ISSUE THREAD

**Issue by adrian-soch** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#15]
Similar to #14 the Verification and Validation Plan Verification Plan section should be a little more specific on how your VnV Plan is going to be reviewed/verified. Perhaps a checklist or something similar can be added.

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `787f920`

**Date Resolved:** `17/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/787f92023beb49505508adb6cd7cb0fb9c4fd693)

### Summary of Changes
Verification and Validation Plan Verification Plan updated with proper detail and a checklist.
