### ISSUE TITLE
VnV Review #5 - System Test Description

### ISSUE THREAD

**Issue by adrian-soch** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#16]
A few comments for Section 4
- All the test IDs are the same, they should have unique names 
- Tests 4.1.1–4.1.3 do not provide inputs or outputs, actual values should be provided such that someone can implement the tests for you
- 4.2.1 is vague in describing the input parameters and expected results for the test

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `20f5245`

**Date Resolved:** `17/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/20f5245df127847b8e6af2a8ee3d07f283536f68)

**Related Issue:** #9 

### Summary of Changes
Updated Section 5.1.1-5.1.3 and 5.2.1.
