### ISSUE TITLE
VnV Review #1 (Duplicate Test IDs)

### ISSUE THREAD

**Issue by XessX** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#17]
Hello!
@WaqarAwan376 

I'm focusing on,
Duplicate Test IDs Across Sections of 4(4.1-4.3) : The use of the same test ID ("test-id1") across different test areas (functional requirements, non-functional requirements) can create confusion and ambiguity. 

Al

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `20f5245`

**Date Resolved:** `17/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/20f5245df127847b8e6af2a8ee3d07f283536f68)

### Summary of Changes
Updated Section 5.1.1-5.1.3 and 5.2.1.
