### ISSUE TITLE
Review: Problem Statement

### ISSUE THREAD

**Issue by WaqarAwan376** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#2]
Requesting your review of the Problem Statement document for this project. Following is the link to the file:

https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/tree/main/docs/ProblemStatementAndGoals

**Comment by smiths** [comment]
Feedback:

- use markdown to link directly to the [problem statement](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf).
- the displacement and velocity are not inputs, the initial velocity and displacement are potential inputs
- is the external force input a function of time?
- the difference between output 1 and 2 is not clear.  I don't think you need output 1 (I don't know what "time evaluation" means.)
- the difference between 2 and 3 is also not clear.  What is the system response?  Isn't that just the displacement and velocity as a function of time?
- are the amplitude and frequency separate outputs?  Are you calculating them from the displacement history?
- your hardware requirements (4GB RAM) don't seem to be based on anything.  How do you know that is what you'll need?  It is better at the requirements stage to not guess at potential hardware constraints.  You can do testing when the software is built to determine the hardware requirements.
- I like the nonlinear goal - I think you should make your requirements for a nonlinear oscillator.  That will give you more to explore.  I suggest you make that stretch goal one of your goals.  We can always simplify it later if necessary.

Your project sounds good.  It is approved.  I look forward to the presentation next week.

**Comment by WaqarAwan376** [comment]
## Issue Update

**Commit ID:** `64d5784`

**Date Resolved:** `02/04/2024`

**Link to Changes:** [View Changes](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/commit/64d5784f562eaa47c615a4c274e183471c566205)

### Summary of Changes
Revised the goals and outputs to align more closely with the project requirements and the feedback received from the instructor.
