### ISSUE TITLE
Review: SRS Document

### ISSUE THREAD

**Issue by WaqarAwan376** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#5]
[Click here to view the document.](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/tree/main/docs/SRS)

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[WaqarAwan_SRS.pdf](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741/files/14389986/WaqarAwan_SRS.pdf)
