### ISSUE TITLE
Issue #6 MG/MIS General 

### ISSUE THREAD

**Issue by FasilCheema** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#51]
General: it would be great to be as specific as possible. If a reader can read this document and implement the code from the documentation; this would be the ideal goal. To this end, it would be great if you can state what each variable is, the type of the variable, and the purpose of certain exceptions and local functions.

**Comment by WaqarAwan376** [comment]
Thank you for the suggestions. I have made an effort to be as specific as possible in the recent updates.
