### ISSUE TITLE
Issue #3 Tracing matrix for Relation between SRS and Modules (Section 8):

### ISSUE THREAD

**Issue by XessX** [WaqarAwan376/Damped_Harmonic_Oscillator-CAS741#54]
A thorough and verified traceability matrix is required between modules and system requirements, and between modules and foreseen changes. This is to ensure complete coverage of system requirements by the modules and the correct formulation and planning of various changes.

**Comment by WaqarAwan376** [comment]
Traceability Matrix(Section 8) is already present on page 7. Please refer to table 2 and table 3 of the document.
